sudo: required
language: python
python:
  - '3.5'
  - '3.6'
services:
  - docker
before_install:
  - docker pull rabbitmq:3-management
  - sudo iptables -N DOCKER || true
  - "docker run -d -h rabbit1 -p 5673:5672 -p 15673:15672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest --name rabbit1 rabbitmq:3-management"
  - docker ps -a
install:
  - pip install flake8 nose>=1.3.0
  - pip install -e .[all]
script:
  - flake8 .
  - python3 setup.py nosetests
